import {
  SCHEDULE_ADDRESS_KEY,
  SCHEDULE_CATEGORY_KEY,
  SCHEDULE_CITY_KEY,
  SCHEDULE_CONTAINER_AMOUNT_KEY,
  SCHEDULE_MATERIAL_AMOUNT_KEY,
  SCHEDULE_MATERIAL_KEY,
  SCHEDULE_REGION_KEY,
} from '@/app/(main)/schedule/_utils/constants';

export type ISchedule = {
  [SCHEDULE_MATERIAL_AMOUNT_KEY]: number;
  [SCHEDULE_ADDRESS_KEY]: string;
  [SCHEDULE_CONTAINER_AMOUNT_KEY]: number;
  [SCHEDULE_CITY_KEY]: string;
  [SCHEDULE_MATERIAL_KEY]: string;
  [SCHEDULE_CATEGORY_KEY]: string;
  [SCHEDULE_REGION_KEY]: string;
};
